name: Deploy to host

on:
  push:
    branches: [ master ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
      
    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find dist/ -print
      
    - name: FTP/SFTP file deployer
      uses: milanmk/actions-file-deployer@1.11
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.HOST }}
        remote-user: ${{ secrets.USERNAME }}
        remote-password: ${{ secrets.PASSWORD }}
        local-path: "./dist"
        remote-path: "/var/www/modern-reader.mrreads.ru"
        sync: "delta"