name: Deploy to host

on:
  push:
    branches: [ master ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
      
    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find dist/ -print
      
    - name: Sync files
        uses: milanmk/actions-file-deployer@master
          with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.HOST }}
          remote-user: ${{ secrets.USERNAME }}
          remote-password: ${{ secrets.PASSWORD }}
          local-path: "/dist/"
          remote-path: "/var/www/modern-reader.mrreads.ru"